# Generated by Django 4.0.6 on 2022-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
