# Generated by Django 4.0.6 on 2022-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitual_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
