# Generated by Django 4.0.6 on 2022-07-31 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inspired', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True, auto_now=True)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('product_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landingpage.products')),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
        migrations.DeleteModel(
            name='InspiredProduct',
        ),
        migrations.DeleteModel(
            name='NewProduct',
        ),
        migrations.DeleteModel(
            name='SummerProduct',
        ),
    ]
