# Generated by Django 4.0.6 on 2022-07-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_products_reviews_delete_featuredproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
