# Generated by Django 4.0.6 on 2022-08-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_alter_reviews_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='username',
            new_name='user',
        ),
    ]
