# Generated by Django 4.0.6 on 2022-08-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingpage', '0008_remove_reviews_user_reviews_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='username',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
